from .. import PRODUCT_NAME_COLUMN_NAME, ISIN_COLUMN_NAME, QUANTITY_COLUMN_NAME, CLOSING_PRICE_COLUMN_NAME, \
    LOCAL_CURRENCY_VALUE_COLUMN_NAME, LOCAL_CURRENCY_NAME_COLUMN_NAME, EURO_VALUE_COLUMN_NAME

DAILY_PORTFOLIO_RESULTS_DUTCH_TO_ENGLISH_COLUMNS = {
    "Product": PRODUCT_NAME_COLUMN_NAME,
    "Symbool/ISIN": ISIN_COLUMN_NAME,
    "Aantal": QUANTITY_COLUMN_NAME,
    "Slotkoers": CLOSING_PRICE_COLUMN_NAME,
    "Lokale waarde": LOCAL_CURRENCY_VALUE_COLUMN_NAME,
    "Lokale valuta": LOCAL_CURRENCY_NAME_COLUMN_NAME,
    "Waarde in EUR": EURO_VALUE_COLUMN_NAME,
}
